name: Build and Deploy
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      name: checkout
    - uses: actions/checkout@master
      with:
        ref: develop

      name: build
      run: |
        npm ci
        npm run build --prefix-paths

    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: master
        folder: public